lib/mak_web/router.ex
defmodule MakWeb.Router do
  use MakWeb, :router
  import MakWeb.Auth, only: [check_admin: 2]

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :auth do
    plug(MakWeb.Guardian.AuthAccessPipeline)
  end

  pipeline :backoffice do
    plug(:check_admin)
  end

  pipeline :landing do
    plug(:put_layout, {MakWeb.LayoutView, "landing.html"})
  end


  # Public
  scope "/", MakWeb do
    pipe_through([:browser, :landing])

    resources("/sessions", SessionController, only: [:new, :create])
    delete("/sessions/drop", SessionController, :drop)
  end

  #

  # Private
  scope "/", MakWeb do
    pipe_through([:browser, :auth])
    get("/", GateController, :index)
    get("/import", ImportController, :machines)

    resources("/m", MachineController) do
      resources("/orders", OrderController, only: [:new])
    end

    resources("/orders", OrderController, only: [:create, :edit, :update, :show])
  end

  # BackOffice
  scope "/bo", MakWeb do
    pipe_through([:browser, :auth, :backoffice])
    get("/", BackofficeController, :index)

    resources("/codes", CodeController)
    resources("/users", UserController)
    resources("/orders", OrderController, only: [:index, :delete])
    get("/change_status/:id", OrderController, :change_status)
  end

  # Other scopes may use custom stacks.
  # scope "/api", MakWeb do
  #   pipe_through :api
  # end
end

lib/mak_web/controllers/backoffice_controller.ex
defmodule MakWeb.BackofficeController do
  use MakWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/mak_web/views/backoffice_view.ex
defmodule MakWeb.BackofficeView do
  use MakWeb, :view
end

lib/mak_web/templates/backoffice/index.html.eex
<div class="row">
  <div class="col-sm-5 col-sm-offset-1 bo_panels">
    <%= link to: user_path(@conn, :index) do %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <span class="glyphicon glyphicon-user" />
        </div>
        <div class="panel-body">
          <h2 style="text-align: center">
            <span class="label label-primary">Gestionar Usuarios</span>
          </h2>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-sm-5 col-sm-offset-1 bo_panels">
    <%= link to: order_path(@conn, :index) do %>
      <div class="panel panel-warning">
        <div class="panel-heading">
          <span class="glyphicon glyphicon-modal-window"/>
        </div>
        <div class="panel-body">
          <h2 style="text-align: center">
            <span class="label label-warning">Gestionar Ordenes</span>
          </h2>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-sm-6 col-sm-offset-3 bo_panels">
    <%= link to: machine_path(@conn, :index) do %>
      <div class="panel panel-success">
        <div class="panel-heading">
          <span class="glyphicon glyphicon-wrench"/>
        </div>
        <div class="panel-body">
          <h2 style="text-align: center">
            <span class="label label-success">Gestionar Máquinas</span>
          </h2>
        </div>
      </div>
    <% end %>
  </div>
</div>