lib/mak_web/router.ex
defmodule MakWeb.Router do
  use MakWeb, :router
  import MakWeb.Auth, only: [check_admin: 2]

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :auth do
    plug(MakWeb.Guardian.AuthAccessPipeline)
  end

  pipeline :backoffice do
    plug(:check_admin)
  end

  pipeline :landing do
    plug(:put_layout, {MakWeb.LayoutView, "landing.html"})
  end


  # Public
  scope "/", MakWeb do
    pipe_through([:browser, :landing])

    resources("/sessions", SessionController, only: [:new, :create])
    delete("/sessions/drop", SessionController, :drop)
  end

  #

  # Private
  scope "/", MakWeb do
    pipe_through([:browser, :auth])
    get("/", GateController, :index)
    get("/import", ImportController, :machines)

    resources("/m", MachineController) do
      resources("/orders", OrderController, only: [:new])
    end

    resources("/orders", OrderController, only: [:create, :edit, :update, :show])
  end

  # BackOffice
  scope "/bo", MakWeb do
    pipe_through([:browser, :auth, :backoffice])
    get("/", BackofficeController, :index)

    resources("/codes", CodeController)
    resources("/users", UserController)
    resources("/orders", OrderController, only: [:index, :delete])
    get("/change_status/:id", OrderController, :change_status)
  end

  # Other scopes may use custom stacks.
  # scope "/api", MakWeb do
  #   pipe_through :api
  # end
end

lib/mak_web/views/layout_view.ex
defmodule MakWeb.LayoutView do
  use MakWeb, :view

  def machine_land?(conn, path) do
    Regex.compile!(path <> "$") |> Regex.match?(Path.join("/", conn.path_info))
  end

end

lib/mak_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Gestión de máquinas">
    <meta name="author" content="José Esteves @ponyesteves">

    <title>Maqs</title>
    <link rel="stylesheet" href="<%= static_path(@conn, ~s[/css/styles.css]) %>">
    <!--  <link rel="manifest" href="<%= static_path(@conn, ~s[/manifest.json]) %>"> -->

  <!-- Add to home screen for Safari on iOS -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Weather PWA">
  <link rel="apple-touch-icon" href="images/icons/icon-152x152.png">
  <meta name="msapplication-TileImage" content="images/icons/icon-144x144.png">
  <meta name="msapplication-TileColor" content="#2F3BA2">

  </head>

  <body>
    <div class="container hidden-print">
      <header class="header">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
          <%= link to: "/" do %>
            <%= img_tag(static_path(@conn, ~s[/images/isowean.png]), class: "logo") %>
          <% end %>
          </div>
        </div>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <div id="my-react-app"> </div>

        <%= render @view_module, @view_template, assigns %>
      </main>

    <nav role="navigation">
    <ul class="nav nav-pills pull-right">
        <li>
          <%= link to: "/", class: "btn btn-success", title: gettext("go home") do %>
            <span class="glyphicon glyphicon-home">
          <% end %>
        </li>
        <%= if machine_land?(@conn, machine_path(@conn, :index)) do %>
        <li>
          <%= link to: import_path(@conn, :machines), class: "btn btn-warning", title: gettext("update") do %>
             <span class="glyphicon glyphicon-refresh">
          <% end %>
        </li>
        <% end %>
        <li>
          <%= link to: session_path(@conn, :drop), method: "delete", class: "btn btn-danger", title: gettext("logout") do %>
            <span class="glyphicon glyphicon-log-out">
          <% end %>
        </li>
      </ul>
    </nav>
    </div> <!-- /container -->
    <div id="print-target-area" class="visible-print-block">

    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/mak_web/templates/layout/landing.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= gettext("Mak App") %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/styles.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= img_tag(static_path(@conn, ~s[/images/isowean.png]), class: "logo") %>
          </div>
        </div>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <div id="my-react-app"> </div>
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
  </body>
</html>