lib/mak_web/router.ex
defmodule MakWeb.Router do
  use MakWeb, :router
  import MakWeb.Auth, only: [check_admin: 2]

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :auth do
    plug(MakWeb.Guardian.AuthAccessPipeline)
  end

  pipeline :backoffice do
    plug(:check_admin)
  end

  pipeline :landing do
    plug(:put_layout, {MakWeb.LayoutView, "landing.html"})
  end


  # Public
  scope "/", MakWeb do
    pipe_through([:browser, :landing])

    resources("/sessions", SessionController, only: [:new, :create])
    delete("/sessions/drop", SessionController, :drop)
  end

  #

  # Private
  scope "/", MakWeb do
    pipe_through([:browser, :auth])
    get("/", GateController, :index)
    get("/import", ImportController, :machines)

    resources("/m", MachineController) do
      resources("/orders", OrderController, only: [:new])
    end

    resources("/orders", OrderController, only: [:create, :edit, :update, :show])
  end

  # BackOffice
  scope "/bo", MakWeb do
    pipe_through([:browser, :auth, :backoffice])
    get("/", BackofficeController, :index)

    resources("/codes", CodeController)
    resources("/users", UserController)
    resources("/orders", OrderController, only: [:index, :delete])
    get("/change_status/:id", OrderController, :change_status)
  end

  # Other scopes may use custom stacks.
  # scope "/api", MakWeb do
  #   pipe_through :api
  # end
end

lib/mak/base/machine.ex
defmodule Mak.Base.Machine do
  use Ecto.Schema
  import Ecto.Changeset
  import MakWeb.Gettext, only: [dgettext: 3]

  @primary_key {:id, :string, []}
  # @derive {Phoenix.Param, key: :id}

  schema "machines" do
    field(:desc, :string)
    field(:name, :string)
    field(:image, :binary)
    has_many(:orders, Mak.Transactions.Order)

    timestamps()
  end

  @doc false
  def changeset(machine, attrs) do
    machine
    |> cast(attrs, [:id, :name, :desc, :image])
    |> validate_image_size(500)
    |> validate_required([:name, :desc])
    |> validate_format(:id, ~r/^\d{7,8}$/)
  end

  defp validate_image_size(changeset, size_limit_kb) do
    changeset
    |> validate_change(:image, fn(:image, image) ->
      cond do
        byte_size(image)/1000 > size_limit_kb -> [image:  dgettext("errors", "image should by smaller than %{size}", size: size_limit_kb)]
        true -> []
      end
    end)
  end
end

lib/mak_web/controllers/machine_controller.ex
defmodule MakWeb.MachineController do
  use MakWeb, :controller

  import MakWeb.Gettext, only: [dgettext: 2]

  alias Mak.Base
  alias Mak.Base.Machine

  def index(conn, params) do
    query = params["q"]
    machines = Base.list_machines(query)
    render(conn, "index.html", machines: machines, query: query)
  end

  def new(conn, _params) do
    changeset = Base.change_machine(%Machine{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"machine" => machine_params}) do
    case Base.create_machine(parse_image(machine_params)) do
      {:ok, machine} ->
        conn
        |> put_flash(:info, dgettext("flash", "La máquina se ha creado correctamente."))
        |> redirect(to: machine_path(conn, :show, machine))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id} = params) do
    machine = Base.get_machine!(id, params["orders_query"])
    changeset = Base.change_machine(machine)
    render(conn, "show.html", machine: machine, changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    machine = Base.get_machine!(id)
    changeset = Base.change_machine(machine)
    render(conn, "edit.html", machine: machine, changeset: changeset)
  end

  def update(conn, %{"id" => id, "machine" => machine_params}) do
    machine = Base.get_machine!(id)

    case Base.update_machine(machine, parse_image(machine_params)) do
      {:ok, machine} ->
        conn
        |> put_flash(:info, dgettext("flash", "Machine updated successfully."))
        |> redirect(to: machine_path(conn, :show, machine))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", machine: machine, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    machine = Base.get_machine!(id)
    {:ok, _machine} = Base.delete_machine(machine)

    conn
    |> put_flash(:info, dgettext("flash", "Machine deleted successfully."))
    |> redirect(to: machine_path(conn, :index))
  end

  defp parse_image(machine_params) do
    image = machine_params["image"]

    case image do
      nil -> machine_params
      _ -> Map.put(machine_params, "image", File.read!(image.path))
    end
  end
end

lib/mak_web/views/machine_view.ex
defmodule MakWeb.MachineView do
  use MakWeb, :view

  def img_from_binary(binary) do
    "data:image/*;base64," <> Base.encode64(binary)
  end
end

lib/mak_web/templates/machine/_home.html.eex
<div class="panel panel-default" style="margin-top:20px">
  <div class="panel-heading">
    <h2>
      <%= @machine.name %>
    </h2>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-sm-6">
        <h4>
          <%= @machine.desc %>
        </h4>
      </div>
      <div class="col-sm-6">
        <%= @machine.image && img_tag(img_from_binary(@machine.image), width: "300px") %>
      </div>
    </div>
    <div class="row">
      <span class="label label-info pull-right">
        <%= @machine.id %>
      </span>
    </div>
  </div>
</div>

lib/mak_web/templates/machine/_orders.html.eex
<%= if(length(@machine.orders) > 0) do %>
<%= form_for @conn, machine_path(@conn, :show, @machine) <> "#orders" , [method: :get], fn f -> %>
  <div class="input-group">
    <span class="input-group-addon" aria-hidden="true">
      <span class="glyphicon glyphicon-search "></span>
    </span>
    <%= search_input f, :orders_query, placeholder: dgettext("forms", "find orders"), class: "form-control" %>
  </div>
<%end%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= dgettext("forms", "status") %></th>
      <th><%= dgettext("forms", "title") %></th>
      <th><%= dgettext("forms", "desc") %></th>
    </tr>
  </thead>
  <tbody>
  <%= for order <- @machine.orders do %>
    <tr onclick="window.goto('<%= order_path(@conn, :edit, order) %>')">
      <td scope="row"><%= order.status.name %></td>
      <td><%= order.title %></td>
      <td><%= order.desc %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% else %>
<div class="row" style="margin-top:20px">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="jumbotron">
      <h3>Esta máquina no tiene ordenes de reparación aún</h3>
    </div>
  </div>
</div>

<% end %>

lib/mak_web/templates/machine/_qr.html.eex
<div class="row">
  <div id="print-area" class="col-md-12" style="margin-top: 40px">
    <div class="pull-left qr-half">
      <%= img_tag("https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=" <> @machine.id, id: "qr") %>
    </div>
    <div class="pull-left qr-half">
      <span><%= @machine.name %></span>
      <br>
      <span><%= @machine.id %></span>
      <br>
      <span>Isowean S.A</span>
    </div>
  </div>
  <%= link to: '#', id: "handle-print", class: "btn btn-warning", title: "Imprimir" do %>
    <span class="glyphicon glyphicon-print">
  <% end %>
</div>
<script type="application/javascript">
  var printArea = document.querySelector('#print-area')

  document.querySelector('#handle-print').addEventListener('click', (_e) => {
  var printTargetArea = document.querySelector('#print-target-area')

    printTargetArea.innerHTML = printArea.innerHTML
    window.print()
  })
</script>

lib/mak_web/templates/machine/edit.html.eex
<h2><%= dgettext("forms", "edit") %> <%= dgettext("forms", "machine")%></h2>

<%= render "form.html", Map.put(assigns, :action, machine_path(@conn, :update, @machine)) %>

<span><%= link dgettext("forms", "back"), to: machine_path(@conn, :index) %></span>

lib/mak_web/templates/machine/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p><%= dgettext("errors","Oops, something went wrong! Please check the errors below." ) %></p>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-6">
      <%= label f, dgettext("forms", "code"), class: "control-label" %>
      <%= text_input f, :id, class: "form-control", readonly: true %>
      <%= error_tag f, :id %>
    </div>
    <div class="col-md-2">
      <%= link "Editar", to: "#", id: "edit_id", class: "btn btn-warning", style: "margin-top: 24px" %>
    </div>
  </div>

  <div class="form-group">
    <%= label f, dgettext("forms", "name"), class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, dgettext("forms", "image"), class: "control-label" %>
    <%= file_input f, :image, class: "form-control", accept: ".jpg,.jpeg,.png" %>
    <%= error_tag f, :image %>
  </div>

  <div class="form-group">
    <%= label f, dgettext("forms", "desc"), class: "control-label" %>
    <%= textarea f, :desc, class: "form-control", rows: 10 %>
    <%= error_tag f, :desc %>
  </div>

  <div class="form-group">
    <%= submit dgettext("forms", "submit"), class: "btn btn-primary" %>
  </div>
<% end %>

<script type="application/javascript">
  document.querySelector('#edit_id').addEventListener('click', (_e) => {
   document.querySelector('#machine_id').readOnly = false
  })
</script>

lib/mak_web/templates/machine/index.html.eex
<%= form_for @conn, machine_path(@conn, :index), [method: :get], fn f -> %>
<div class="row">
  <div class="col-md-6">
    <div class="input-group">
      <span class="input-group-addon" aria-hidden="true">
        <span class="glyphicon glyphicon-search "></span>
      </span>
      <%= search_input f, :q, placeholder: dgettext("forms", "find machine"), class: "form-control" %>
    </div>
  </div>
  <div class="col-md-offset-2 col-md-4">
    <%= link "Agregar Máquina", to: machine_path(@conn, :new), class: "btn btn-danger", style: "width: 100%" %>
  </div>
</div>

<% end %>
<div class="row">

<%= for machine <- @machines do %>
<div class="col-md-3">
  <div class="panel panel-primary" onclick="window.goto('<%= machine_path(@conn, :show, machine) %>')">
    <div class="panel-heading" style="height:80px">
      <%= machine.name %>
      <span class="badge pull-right"><%= machine.id %>
    </span></div>
      <div class="panel-body" style="height:100px">
        <p><%= String.slice(machine.desc, 0..40) <> "  ..." %> </p>
      </div>
    </div>
  </div>
<% end %>
</div>

lib/mak_web/templates/machine/new.html.eex
<h2><%= dgettext("forms", "new") %> <%= dgettext("forms", "machine")%></h2>

<%= render "form.html", Map.put(assigns, :action, machine_path(@conn, :create)) %>

<span><%= link dgettext("forms", "back"), to: machine_path(@conn, :index) %></span>

lib/mak_web/templates/machine/show.html.eex
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active">
    <a href="#home" aria-controls="home" role="tab" data-toggle="tab">
      <span class="glyphicon glyphicon-home" />
    </a>
  </li>
  <li role="presentation">
    <a href="#orders" aria-controls="orders" role="tab" data-toggle="tab">
      <span class="glyphicon glyphicon-paperclip" />
    </a>
  </li>
  <%# <li role="presentation">
    <a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">
      <span class="glyphicon glyphicon-comment" />
    </a>
  </li> %>
  <li role="presentation">
    <a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">
      <span class="glyphicon glyphicon-edit" />
    </a>
  </li>
  <li role="presentation">
    <a href="#qr" aria-controls="home" role="tab" data-toggle="tab">
      <span class="glyphicon glyphicon-qrcode" />
    </a>
  </li>
  <li role="presentation" class="pull-right">
    <%= link dgettext("forms", "new") <> " " <> dgettext("forms", "order"), to: machine_order_path(@conn, :new, @machine), class: "btn btn-danger pull-right" %>
  </li>
</ul>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="home">
    <%= render "_home.html", conn: @conn, machine: @machine %>
  </div>
  <div role="tabpanel" class="tab-pane" id="orders">
    <%= render "_orders.html", conn: @conn, machine: @machine %>
  </div>
  <div role="tabpanel" class="tab-pane" id="messages">
    ...
  </div>
  <div role="tabpanel" class="tab-pane" id="settings">
    <%= render "form.html", Map.put(assigns, :action, machine_path(@conn, :update, @machine)) %>
  </div>
  <div role="tabpanel" class="tab-pane" id="qr">
    <%= render "_qr.html", machine: @machine %>
  </div>
</div>